#!/bin/sh

cat > ../programs/upload_elf.c <<EOF
// THIS FILE IS AUTOGENERATED BY upload_program.sh
#include <stdint.h>
#include <stddef.h>
#include "file/file.h"
#include "upload_elf.h"

// This array will be filled with the contents of hello.elf
EOF

# Convert hello.elf to a C array
xxd -i ../programs/hello.elf >> ../programs/upload_elf.c

cat >> ../programs/upload_elf.c <<EOF

void upload_hello_elf(void) {
    filesystem_make_binary("hello.elf", ___programs_hello_elf, sizeof(___programs_hello_elf));
}
EOF